### ISSUE TITLE
Building AQL. autoreconf: error: 'configure.ac' is required

### ISSUE THREAD

**Issue by vdiravka** [aerospike/aql#21]
```
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
```
Installed `sudo apt-get install libreadline8 libreadline-dev flex` and cloned the project.

```
/aql$ make clean
/aql$ make
cd ./modules/jansson && autoreconf -i
autoreconf: error: 'configure.ac' is required
make: *** [Makefile:163: modules/jansson/configure] Error 1
```

**Comment by jdogmcsteezy** [comment]
Hey @vdiravka, thanks for the question. What do you see in the directory `modules/jansson`?  I suspect that you either need to run `git submodule update --recursive --init` or `configure.ac` was somehow deleted

**Comment by jdogmcsteezy** [comment]
Closing. Please re-open if the issue remains
